# Scegli un'immagine Windows moderna che ha già molti strumenti
image: Visual Studio 2022

# Fase di installazione: qui prepariamo l'ambiente
install:
  - ps: Write-Host "Installing Inno Setup..."
  - choco install innosetup -y

build_script:
  # Usiamo 'cmd:' per assicurarci di essere in un ambiente Command Prompt.
  # Lanciamo lo script con il parametro che abbiamo aggiunto per l'automazione.
  - cmd: 'build.bat -fullbuild'

# Fase degli artefatti: qui raccogliamo i file creati
artifacts:
  # Raccoglie l'installer e gli dà un nome di riferimento "Installer"
  - path: build\*-setup.exe
    name: Installer
  - path: 'build\*-setup.exe.sha256.txt'
    name: Checksum
  # Raccoglie il log per il debug
  - path: build.log

deploy:
  - provider: GitHub
    tag: continuous
    release: continuous
    auth_token:
      secure: j2wYgDHRlxXaLB8MjsM3l2T+KlBA441m1r9g5cdo6nNh36f7w+iRlUv6eDtNB332
